name: acoustic
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.2.0+0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_screenutil: '5.1.0'
  country_code_picker: ^2.0.2
  cached_network_image: ^3.0.0
  flutter_spinkit: ^5.0.0
  flutter_staggered_grid_view: ^0.4.0
  image_picker: ^0.8.2
  fluttertoast: ^8.0.7
  carousel_slider: ^4.0.0
  retrofit: ^2.0.0
  connectivity: ^3.0.6
  flutter_switch: ^0.3.2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  permission_handler: ^8.1.2
  intl: ^0.17.0
  onesignal_flutter: ^3.2.8
  image_downloader: ^0.31.0
  gallery_saver: ^2.1.2
  marquee: ^2.2.0
  video_player: ^2.1.10
  share: ^2.0.4
  underline_indicator: ^0.0.4
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  # camera: ^0.9.4+19
  camera: ^0.9.4+10
  # camera: ^0.10.0+1
  assets_audio_player: ^3.0.4+1
  path_provider: ^2.0.2
  path: ^1.8.0
  video_compress: ^3.1.0
  circular_countdown_timer: ^0.2.0
  video_trimmer: ^0.6.0
  firebase_core_platform_interface: ^4.5.1

#  deprecated lib
  flutter_ffmpeg: ^0.4.0
#  ffmpeg_kit_flutter: ^4.5.1
#  native_admob_flutter: ^1.4.1

  # google_mobile_ads: ^2.0.0
  google_mobile_ads:
    git:
      url: https://github.com/jjliu15/googleads-mobile-flutter-1.git
      path: packages/google_mobile_ads/
  facebook_audience_network:
  # facebook_audience_network: ^1.0.1
  flutter_svg: ^0.22.0
  location: ^4.3.0 
  file_picker: ^4.6.1
  uni_links: ^0.5.1
  firebase_storage: ^11.0.3
  provider: ^6.0.1
  photo_view: ^0.12.0
  shared_preferences: ^2.0.13
#  flutter_native_splash: ^2.1.5
  flutter_native_splash: ^2.2.0
  flutter_html: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  fimber: ^0.6.1
  json_serializable: ^4.1.3
  retrofit_generator: ^2.0.0+3
  build_runner: ^2.0.6
  kiwi_generator: ^3.0.0
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.4


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path:  "images/main_logo.png"

flutter_native_splash:
  color: "#121212"
  image: images/splash_image.png
#  background_image: assets/images/zomox_splash.png
  color_dark: "#121212"
  image_dark: images/splash_image.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectfill



  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    color: "#121212"
    image: images/splash_image.png
  # The image parameter sets the splash screen icon image.  If this parameter is not specified,
  # the app's launcher icon will be used instead.
  # Please note that the splash screen will be clipped to a circle on the center of the screen.
  # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
  # 640 pixels in diameter.
  # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
  # 768 pixels in diameter.
  #image: assets/android12splash.png

  # App icon background color.
  icon_background_color: "#121212"

  # The image_dark parameter and icon_background_color_dark set the image and icon background
  # color when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above.
  #image_dark: assets/android12splash-invert.png
  #icon_background_color_dark: "#eeeeee"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center

  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  fonts:
    - family: Proxima
      fonts:
        - asset: fonts/ProximaNova-Regular.otf

    - family: ProximaBold
      fonts:
        - asset: fonts/Proxima Nova Bold.otf


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
